name: pay_offline
description: A fully offline payments app using Flutter and Hive.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true


